import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "../styles/globals.css";

const figTreeSans = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${figTreeSans.variable} ${figTreeSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
